# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gasprom.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(791, 322)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget {\n"
"    \n"
"    background-color: white;\n"
"    \n"
"}")
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    background-color: #ff26c6dc;\n"
"    /*font-family: \"Bahnschrift Light Condensed\";*/\n"
"    color: white;\n"
"    /*border-radius: 7px;*/\n"
"    padding: 3px;\n"
"    \n"
"}")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    background-color: #ff26c6dc;\n"
"    /*font-family: \"Bahnschrift Light Condensed\";*/\n"
"    color: white;\n"
"    /*border-radius: 7px;*/\n"
"    padding: 3px;\n"
"    \n"
"}")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.comboBox_3 = QtWidgets.QComboBox(self.page)
        self.comboBox_3.setGeometry(QtCore.QRect(10, 60, 369, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        self.comboBox_3.setStyleSheet("QComboBox {\n"
"    border: 1px solid #ffaeb7c0;\n"
"    border-radius: 3px;\n"
"    padding: 3px;\n"
"}")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.comboBox_4 = QtWidgets.QComboBox(self.page_2)
        self.comboBox_4.setGeometry(QtCore.QRect(10, 60, 369, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_4.sizePolicy().hasHeightForWidth())
        self.comboBox_4.setSizePolicy(sizePolicy)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.comboBox_5 = QtWidgets.QComboBox(self.page_3)
        self.comboBox_5.setGeometry(QtCore.QRect(10, 60, 369, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_5.sizePolicy().hasHeightForWidth())
        self.comboBox_5.setSizePolicy(sizePolicy)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.stackedWidget.addWidget(self.page_3)
        self.horizontalLayout_3.addWidget(self.stackedWidget)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_2.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_2.setSizePolicy(sizePolicy)
        self.plainTextEdit_2.setStyleSheet("QPlainTextEdit {\n"
"    border: 1px solid #ffaeb7c0;\n"
"    border-radius: 10 1px;\n"
"    padding: 3px;\n"
"}")
        self.plainTextEdit_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.plainTextEdit_2.setLineWidth(1)
        self.plainTextEdit_2.setUndoRedoEnabled(False)
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.horizontalLayout_3.addWidget(self.plainTextEdit_2)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.comboBox.setStyleSheet("QComboBox {\n"
"    border: 1px solid #ffaeb7c0;\n"
"    border-radius: 3px;\n"
"    padding: 3px;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setStyleSheet("QComboBox {\n"
"    border: 1px solid #ffaeb7c0;\n"
"    border-radius: 3px;\n"
"    padding: 3px;\n"
"}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_2)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #fff58d4e;\n"
"    /*font-family: \"Bahnschrift Light Condensed\";*/\n"
"    color: white;\n"
"    border-radius: 7px;\n"
"    padding: 7px;\n"
"    /*border: 1px solid #ff674c3c;\n"
"    margin-right: 7px;\n"
"    margin-left: 7px;*/\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #ff30c3b1;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff2cb0a0;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_5, 6, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    background-color: #ff30c3b1;\n"
"    /*font-family: \"Bahnschrift Light Condensed\";*/\n"
"    color: white;\n"
"    border-radius: 3px;\n"
"    padding: 6px;\n"
"    \n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Переводчикус"))
        self.label_3.setText(_translate("MainWindow", "Из:"))
        self.label_2.setText(_translate("MainWindow", "В:"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "A"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "A*"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "A**"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "B1"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "B2"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "B1*"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "B2*"))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "C1"))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "C2"))
        self.comboBox_3.setItemText(9, _translate("MainWindow", "C1**"))
        self.comboBox_3.setItemText(10, _translate("MainWindow", "C2**"))
        self.comboBox_3.setItemText(11, _translate("MainWindow", "D0"))
        self.comboBox_3.setItemText(12, _translate("MainWindow", "D1"))
        self.comboBox_3.setItemText(13, _translate("MainWindow", "D2"))
        self.comboBox_3.setItemText(14, _translate("MainWindow", "Dл"))
        self.comboBox_3.setItemText(15, _translate("MainWindow", "D0**"))
        self.comboBox_3.setItemText(16, _translate("MainWindow", "D1**"))
        self.comboBox_3.setItemText(17, _translate("MainWindow", "D2**"))
        self.comboBox_3.setItemText(18, _translate("MainWindow", "Dл**"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Осуществимые проекты, ведется добыча (F1.1, E1.1/E1.2)"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Осуществимые проекты, утверждён к разработке (F1.2, E1.1/E1.2)"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "Осуществимые проекты, обоснован к разработке (F1.3, E1.1/E1.2) "))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "Потенциально осуществимые проекты, ожидает разработки (F2.1, E1.1; F1.3/2.1, E2)"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "Потенциально осуществимые проекты, разработка задерживается (F2.2, E2)"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "Неосуществимые проекты, неясные планы по разработке (F1.3/2.1/2.2, E3.2)"))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "Неосуществимые проекты, разработка неосуществима (F1.3-2.3, E3.3)"))
        self.comboBox_4.setItemText(7, _translate("MainWindow", "Перспективные проекты, подготовленная структура (F3.1, E3.2)"))
        self.comboBox_4.setItemText(8, _translate("MainWindow", "Перспективные проекты, недостаточно изученная структура (F3.2, E3.2)"))
        self.comboBox_4.setItemText(9, _translate("MainWindow", "Перспективные проекты, территория поисково-разведочных работ (F3.3, E3.2)"))
        self.comboBox_4.setItemText(10, _translate("MainWindow", "Недобытая остаточная продукция в рамках известных/перспективных проектов (F4, E3.3)"))
        self.comboBox_4.setItemText(11, _translate("MainWindow", "Добыто, не продано (F1.1-2.3, E3.1)"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Открытые, коммерчески целесообразные (запасы)"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "Открытые, коммерчески нецелесообразные (условные ресурсы)"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "Открытые, неизвлекаемые ресурсы"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "Неоткрытые, перспективные ресурсы"))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "Неоткрытые, неизвлекаемые ресурсы"))
        self.comboBox_5.setItemText(5, _translate("MainWindow", "Определены, но не классифицированы в PRMS"))
        self.comboBox.setItemText(0, _translate("MainWindow", "РФ-2013"))
        self.comboBox.setItemText(1, _translate("MainWindow", "РКООН"))
        self.comboBox.setItemText(2, _translate("MainWindow", "PRMS"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "РФ-2013"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "РКООН"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "PRMS"))
        self.pushButton.setText(_translate("MainWindow", "Перевести"))
        self.label.setText(_translate("MainWindow", "Перевод количеств углеводородов между основными классификациями запасов и ресурсов"))
import res_rc
